package com.job.enums;

public enum NotificationType {
    APPLICATION_RECEIVED,
    APPLICATION_STATUS_CHANGED,
    JOB_RECOMMENDATION,
    PROFILE_VISIT,
    CONNECTION_REQUEST,
    MESSAGE_RECEIVED,
    JOB_EXPIRED,
    PREMIUM_EXPIRING,
    PAYMENT_SUCCESSFUL,
    PAYMENT_FAILED
}
